### PR TITLE
Animation, Animated mesh loading and texturing

### PR DESCRIPTION
**Pull request by DelCherub**
-GameObjects now have an attached AnimatorObject which handles the animation for that object. An animator object contains information about the current animation, the current frame of animation and the animation speed, and will update the current frame of animation with UpdateAnimation. Further work could be good to add animation transitions.
- Textures for animated meshes may be upside down due to how OpenGL loads textures: we will have to figure out what needs changed once we start working with PS5 rendering
- The RenderObject of a GameObject has reference to the AnimatorObject, so it can get animation information from it when rendering. It also has a reference to the MeshMaterial it should use when rendering the mesh.
- Resources.cpp now also holds MeshMaterials and Animations.
- A Mesh should have a map of all the animations that it can play, so when assigning an animation to an AnimatorObject, only animations for that mesh can be used. See GameplayState.CreatePlayers() for an example of animations being assigned. Currently, this is not set up properly: perhaps a data driven approach would be helpful such that each mesh file has an accompanying animation file which holds the paths of animations it can use? A function on startup to load a mesh's animations would be good.

### CODE REVIEW

**Review by Odycious — APPROVED** [review]

**Review by Odycious — CHANGES_REQUESTED** [review]
The code worked fine on your branch, however, when merging main into your branch the other rendering ceased to work. For example, the platforms for the level do not render.

**Comment by DelCherub** [comment]
> The code worked fine on your branch, however, when merging main into your branch the other rendering ceased to work. For example, the platforms for the level do not render.

I'll look into that

**Comment by DelCherub** [comment]
Fixed problems yaaaaaaay

**Review by Odycious — APPROVED** [review]
Good fixes, thanks for making the changes!

**Pull request merged**
